nextflow run main.nf \
    --meta HPV \
    --outdir result/ \
    --data_type combined \
    --split_data_by design \
    --design /home/bdkhoi/projects/transcriptomics_classifier/data/112_samples/design_full.csv \
    --human_countdata /home/bdkhoi/projects/transcriptomics_classifier/data/112_samples/human_counts.csv \
    --viral_countdata /home/bdkhoi/projects/transcriptomics_classifier/data/112_samples/viral_counts.csv \
    --inference_count /home/bdkhoi/projects/transcriptomics_classifier/data/inference/clean_count.csv \
    --inference_design /home/bdkhoi/projects/transcriptomics_classifier/data/inference/design.csv \
    -resume 2>&1 | tee headnode.log